# STATS 507 · Week5-1: Intro to NumPy in-class practice

You are preparing a sales report. Rows represent stores; columns represent three days, from oldest to newest. Negative values are recording errors.

Run the setup cell, then work through the questions in order. Use NumPy operations without loops or list comprehensions. No function definitions are needed.

Save your answers using the variable names specified below. Run the test cell at the end of each question after completing your code. Tests check the code results; discuss the written explanations separately.

In [2]:
import numpy as np

stores = np.array(["A", "B", "C", "D"])
sales = np.array([
    [10, -2, 20],  # Store A
    [ 5, 25,  0],  # Store B
    [20, 10, 30],  # Store C
    [-3,  0, 20],  # Store D
])

sales

array([[10, -2, 20],
       [ 5, 25,  0],
       [20, 10, 30],
       [-3,  0, 20]])

## 1. Inspect and select

1. Display `sales.shape` and explain what each entry represents.
2. Select Day 2 sales for all stores as a one-dimensional array named `day2`.
3. Select the last two days for the first two stores as a two-dimensional array named `recent_sales`.

In [3]:
# Display and explain sales.shape:
print(sales.shape)
print('The first one is row number and the second one is column number')
# Select Day 2 and save as day2:
day2 = sales[:, 1]
print(day2)
# Select the first two stores and last two days; save as recent_sales:
recent_sales = sales[:2, -2:]
print(recent_sales)

(4, 3)
The first one is row number and the second one is column number
[-2 25 10  0]
[[-2 20]
 [25  0]]


In [4]:
# Quick check for Question 1
assert np.array_equal(day2, [-2, 25, 10, 0])
assert np.array_equal(recent_sales, [[-2, 20], [25, 0]])
print("Question 1 passed!")

Question 1 passed!


## 2. Find and fix recording errors 

1. Create a Boolean array `invalid` that identifies negative entries. Use it to display the invalid values.
2. Create `cleaned` as a copy of `sales` and replace all negative entries with zero.
3. Display `cleaned` and check that `sales` still contains the original values.

**Explain briefly:** Why use `sales.copy()` instead of `cleaned = sales`?

In [5]:
# Create invalid and display the negative values:
invalid = sales < 0
print(sales[invalid])
# Copy sales and fix the invalid entries:
cleaned = sales.copy()
cleaned[invalid] = 0
# Display cleaned and sales:


[-2 -3]


**Your explanation:**


In [6]:
# Quick check for Question 2
assert np.array_equal(cleaned, [[10, 0, 20], [5, 25, 0], [20, 10, 30], [0, 0, 20]])
assert np.array_equal(sales, [[10, -2, 20], [5, 25, 0], [20, 10, 30], [-3, 0, 20]])
print("Question 2 passed!")

Question 2 passed!


## 3. Update the report

Some sales were omitted: **2 per store on Day 1, 0 on Day 2, and 1 on Day 3**.

1. Add the provided `extra` array to `cleaned` to create `updated`.
2. Compute `store_totals`: one total per store across all days.
3. Compute `day_totals`: one total per day across all stores.

Choose the appropriate `axis` for each sum. Explain why `extra` can be added to every row even though its shape differs from `cleaned.shape`.

**Quick check:** Store A's updated total should be **33**.

In [12]:
extra = np.array([2, 0, 1])

# Create updated:
updated = cleaned + extra
# Compute and display store_totals and day_totals:
store_totals = np.sum(updated, axis=1)
day_totals = np.sum(updated, axis=0)

**Your explanation:**


In [13]:
# Quick check for Question 3
assert np.array_equal(store_totals, [33, 33, 63, 23])
assert np.array_equal(day_totals, [43, 35, 74])
print("Question 3 passed!")

Question 3 passed!


## 4. Select stores for a follow-up
Using `updated` and `store_totals`, find stores that satisfy **both** conditions:

- Their total sales are **at least 25**.
- Their Day 3 sales are **at least 15**.

Create one Boolean mask called `selected`. Use it to save the qualifying store names as `selected_stores` and their rows from `updated` as `selected_sales`, preserving the original order. Display both arrays.

**Think before running:** Which stores do you expect to qualify?

*Hint: Combine Boolean arrays with `&` and put parentheses around each comparison.*

In [22]:
# My prediction:

# Create selected:
selected = (store_totals >= 25) & (updated[:, 2] >= 15)
# Create and display selected_stores and selected_sales:
selected_stores = stores[selected]
selected_sales = updated[selected]

In [23]:
# Quick check for Question 4
assert np.array_equal(selected_stores, ["A", "C"])
assert np.array_equal(selected_sales, [[12, 0, 21], [22, 10, 31]])
print("Question 4 passed!")

Question 4 passed!
